name: Build

on:
  push:
    branches:
    - master

jobs: 
  Win32:
    runs-on: windows-latest
    steps:
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build --config Release
        
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build --config Release
      
  Macos:
    runs-on: macos-latest
    steps:
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build --config Release
       
