name: Build

on:
  push:
    branches:
    - master

jobs: 
  App:
    strategy:
      matrix:    
        config: [{os: windows-latest, cpp: g++, c: gcc},{os: windows-latest, cpp: cl, c: cl},{os: ubuntu-latest, cpp: g++, c: gcc},{os: ubuntu-latest, cpp: clang++, c: clang},{os: macos-latest, cpp: g++, c: gcc},{os: macos-latest, cpp: clang++, c: clang}]
    runs-on: ${{ matrix.config.os }}
    steps:
    - name: configure
      env:
        CC: ${{ matrix.config.c }}
        CXX: ${{ matrix.config.cpp }}
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build --config Release
